#!/usr/bin/env python3

from spotipy.oauth2 import SpotifyOAuth
import spotipy
import time
import pprint

scope = "user-read-playback-state,user-modify-playback-state"
spotifyClient = spotipy.Spotify(client_credentials_manager=SpotifyOAuth(scope=scope))

songName = input("Enter song name: ")
startTime = int(input("Enter loop start time: "))
endTime = int(input("Enter loop end time: "))
loopTime = endTime - startTime

result = spotifyClient.search(q=songName,
                   limit=1,
                   type="track")

songURI = result["tracks"]["items"][0]["uri"]

spotifyClient.start_playback(
    uris=[songURI],
    position_ms=startTime * 1000
)

while (True):
    time.sleep(loopTime)
    print("Loop!")
    spotifyClient.seek_track(startTime * 1000)

